<p>
    <?php
        if (array_key_exists('message', $_SESSION)) {
            echo $_SESSION['message'];
            unset($_SESSION['message']);
        }
    ?>
</p>

<form role="form" role="form" method="post" action="<?php echo $this->url('login'); ?>">
    Número do cartão: <input type="text" name="numero-cartao">
    Senha: <input type="text" name="senha">
    <input type="submit" value="Entrar"> <input type="reset" value="Limpar">
</form>
